### ISSUE TITLE
 For loop has some redundancies.

### ISSUE THREAD

**Issue by ZeynepErguven** [sarahann0032/SPM24#5]
The loop condition (total <= 5) is already controlled by the total += 1 statement inside the loop. This causes the loop to run an extra iteration when total becomes 6, printing an extra line (Total = 6).

**Comment by ZeynepErguven** [comment]
The variable i is declared but is not actually used inside the loop, making it redundant.

**Comment by sarahann0032** [comment]
We still have this issue

**Comment by sarahann0032** [comment]
We still have this issue
